services:
  grafana:
    image: grafana/grafana-enterprise:latest     # Linux-based docker image
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
    restart: unless-stopped
