xglobal:
  scrape_interval: 15s

rule_files:
  - "recording-rules.yml"

remote_write:
  - url: http://localhost:9090/api/v1/write
    queue_config:
      max_samples_per_send: 1000
      max_shards: 200
      capacity: 2500

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
