networks:
  grafana:

volumes:
  grafana_data: {}

services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    networks:
      - grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana.ini:/etc/grafana/grafana.ini
      - ./customHomeDashboard.json:/var/lib/grafana/dashboards/customHomeDashboard.json
    user: "472:472"
